[project]
site_name = "Kvalitet i kode og koding"
site_description = "Regler, anbefalinger og veiledninger for kvalitet i kode og koding i SSB."
docs_dir = "docs"
site_dir = "site"
extra_css = ["assets/stylesheets/extra.css"]

[project.theme]
variant = "modern"
language = "nb"
features = [
  "navigation.indexes",
  "navigation.sections",
  "navigation.top",
  "search.highlight",
  "content.code.copy",
]

[project.validation]
invalid_links = true
invalid_link_anchors = true
